# ## installing pacakages
# install.packages("devtools")
# install.packages("dplyr")
# install.packages("tidyverse")
# install.packages('caTools')
# install.packages('kernlab')
# install.packages ('caret')
# install.packages ('kknn')
# install.packages("factoextra")
# install.packages("tree")
# install.packages("rpart.plot")
# install.packages ("randomForest")
# install.packages("aod") 
# install.packages("ROCR")
# install.packages("naniar")
# install.packages("mice")
# install.packages("Ecdat")
# ##Loading packages

library(devtools)
library (dplyr)
library(tidyverse)
library(caTools)
library(kernlab)
library(caret)
library(class)
library (kknn)
library(factoextra)
library(rpart)
library(tree)
library(rpart.plot)
library(caTools)
library(tree)
library(randomForest)
library(aod)
library(ROCR)
library(naniar)
library(Hmisc)
library (mice)
library(Ecdat)

2+3

print("All packages loaded")